import Foundation

struct DailyContent {
    static let quotes: [String] = [
        "Life moves pretty fast. If you don’t stop and look around once in a while, you could miss it. - Ferris Bueller",
        "If you focus on what you left behind, you will never be able to see what lies ahead. - Gusteau",
        "Yesterday is history, tomorrow is a mystery, but today is a gift. That is why it is called the present. - Master Oogway",
        "Just keep swimming. - Dory",
        "You are braver than you believe, stronger than you seem, and smarter than you think. - Christopher Robin",
        "To infinity… and beyond! - Buzz Lightyear",
        "Oh yes, the past can hurt. But you can either run from it, or learn from it. - Rafiki",
        "The flower that blooms in adversity is the most rare and beautiful of all. - The Emperor of China",
        "Adventure is out there! - Ellie Fredricksen",
        "Sometimes the right path is not the easiest one. - Grandmother Willow",
        "I can do this all day. - Steve Rogers",
        "Genius, billionaire, playboy, philanthropist. - Tony Stark",
        "We never lose our demons, we only learn to live above them. - The Ancient One",
        "No amount of money ever bought a second of time. - Tony Stark",
        "Part of the journey is the end. - Tony Stark",
        "The hardest choices require the strongest wills. - Thanos",
        "I choose to run toward my problems, and not away from them. - Thor",
        "Do. Or do not. There is no try. - Yoda",
        "Your focus determines your reality. - Qui-Gon Jinn",
        "Never tell me the odds. - Han Solo",
        "The Force will be with you. Always. - Obi-Wan Kenobi",
        "In my experience, there is no such thing as luck. - Obi-Wan Kenobi",
        "Why do we fall? So we can learn to pick ourselves up. - Alfred Pennyworth",
        "It’s not who I am underneath, but what I do that defines me. - Bruce Wayne",
        "With great power comes great responsibility. - Uncle Ben",
        "Hope is a good thing, maybe the best of things. - Andy Dufresne"
    ]

    static let questionsOfTheDay: [String] = [
        "What's the most embarrassing song on your playlist that you secretly love?",
        "What's the weirdest or most random thing on your bucket list?",
        "If you could have any animal as a sidekick, which one would it be and what would you name it?",
        "What's the strangest food combination you've ever tried and actually enjoyed?",
        "If your life had a theme song, what would it be?",
        "What's the most unusual talent or skill you possess that not many people know about?",
        "If you had to create a new holiday, what would it be called, and how would people celebrate it?",
        "If you could choose one fictional world to live in, which one would it be, and how would you fit into that universe?",
        "If you could have a remote control that only worked on people, what button(s) would you want it to have?",
        "What's the most embarrassing thing you've ever done in public?",
        "If you could switch lives with any cartoon character for a day, who would it be and why?",
        "What's your go-to karaoke song, and can you give us a quick rendition right now?",
        "What's the strangest dream you've ever had that still lingers in your memory?",
        "If your pet could talk, what's the first question you'd ask them?",
        "What's the most bizarre talent or skill you wish you had, even though it's totally impractical?",
        "What's your favorite dad joke, and can you share it with us?",
        "If you were a punctuation mark, which one would you be, and why?",
        "What's your secret obsession that you're willing to admit to right now?",
        "If you could have dinner with any historical figure, who would it be, and what's the first question you'd ask them?",
        "If you had to live in a different century, which one would you choose, and what would be your occupation there?",
        "What's the most ridiculous thing you've bought online while under the influence of late-night shopping?",
        "What's your most embarrassing nickname, and how did you earn it?",
        "What's your guilty pleasure TV show or movie that you secretly enjoy?",
        "If you could give one piece of advice to your younger self, what would it be?",
        "What's your weirdest fear, even if it's completely irrational?",
        "What's your weirdest habit that you're proud of and refuse to change?",
        "If you could create your own world record, what would it be for?",
        "If you could swap lives with a famous movie/tv/video game character for a day, who would it be and why?",
        "What's the weirdest thing you've ever named, like a plant or an inanimate object, and why did you choose that name?",
        "If you were a professional athlete, in which sport would you compete, and what would your victory celebration be like?",
        "What's the most bizarre thing you've ever witnessed while people-watching in a public place?",
        "What's the silliest thing you believed as a child that you wish were true as an adult?",
        "If you could have any animal as a mode of transportation, which one would you choose, and why?",
        "If you could make a cameo in any TV show/Movie/Video Game, which show would it be, and what would your character's role be?",
        "If you could have a conversation with any fictional character, who would it be, and what would you talk about?",
        "If you could turn any everyday activity into an Olympic sport, what would it be, and what would your strategy be?",
        "What's the strangest item you've ever won?",
        "If you could have a conversation with a talking inanimate object, what would it be, and what would you ask it?",
        "If you had to create your own nation, what would it be called, and what would be its national anthem?",
        "What's your superstitious ritual that you believe brings good luck?",
        "What's the funniest thing that's ever happened to you?",
        "What's the most unique item you've ever collected or hoarded?",
        "If you could create a new word and have it added to the dictionary, what would it mean, and how would you use it in a sentence?",
        "What's the most peculiar thing you've ever found at a garage sale or thrift store?",
        "If you were a mad scientist, what bizarre experiment would you conduct in your laboratory?",
        "If your favorite childhood toy came to life, what would they say about you now?",
        "What’s something you would do if you knew there’d be absolutely no consequences?",
        "If you could listen in on any conversation from history, which one would you choose?",
        "If you could have one day where everyone in the world took you 100% seriously, what would you do?",
        "If you could master any skill instantly, no matter how bizarre, what would it be?",
        "What’s a life lesson you wish you’d learned earlier?",
        "What’s the most out-of-character thing you’ve ever done, and why did you do it?",
        "If you could make one tradition from your childhood universal, what would it be?",
        "What’s the most ridiculous argument you've ever had that you still think you were right about?",
        "If you could only describe your personality using movie titles, what three would you pick?",
        "What's the strangest piece of advice you've ever received that actually helped you?",
        "What's a simple pleasure that makes your day infinitely better?",
        "If you could relive one day exactly as it happened, without changing anything, what day would you pick?",
        "If you could meet any version of yourself from the past or future, which one would it be, and why?",
        "What's one fact about you that would surprise even your closest friends?",
        "If you could pick one random skill or hobby to be exceptionally good at, what would it be and why?",
        "If you could spend a week learning from any expert in the world, who would it be, and what would you learn?",
        "What’s one thing you secretly love that most people think is a bit silly?",
        "If you could ask a single question to a stranger and get a totally honest answer, what would you ask?",
        "If you could invent a gadget that made one daily task easier, what would it do?",
        "What’s a piece of popular advice that you completely disagree with?",
        "If you could travel back in time to witness any event firsthand, which one would you pick?",
        "What’s a totally useless skill you have that you’re secretly proud of?",
        "If you could have any artist (past or present) paint your portrait, who would you choose and why?",
        "What’s the funniest misunderstanding you’ve ever had with someone?",
        "If you had to write a conspiracy theory about yourself, what would it be?",
        "What’s the kindest thing anyone’s ever done for you that you’ll never forget?",
        "If your mind worked like a search engine, what’s the most frequent search?",
        "If your mind worked like a search engine, what would be the last search?",
        "What’s the most exciting risk you’ve ever taken?",
        "If you could instantly acquire fluency in one language, which would you choose and why?",
        "If you could create one change to make life easier for everyone, what would it be?",
        "What's the most nostalgic smell for you, and where does it take you?",
        "If you could solve one mystery of the world, which would you pick?",
        "What's one habit or activity you wish you could quit but find oddly enjoyable?",
        "If you could get advice from anyone in history, who would you choose and what would you ask?",
        "What's something simple that never fails to make you feel a little better?",
        "What’s one mistake you’re actually glad you made?",
        "If you were to open a themed café, what would the theme be, and what would be on the menu?",
        "What's the one fictional character you wish was real, and why?",
        "If you had to pick one color to wear for the rest of your life, what would it be, and why?",
        "If you could bring one extinct animal back to life, which one would you choose, and where would you keep it?",
        "If you could live inside any painting, which one would it be, and what would you do there?",
        "If you could make up a word for an everyday feeling that doesn’t have one, what would it be?",
        "What's something that you've done once but would never want to do again?",
        "What’s a rule you follow that no one else seems to understand?",
        "If you were a piece of furniture, what would you be, and why?",
        "If you could listen to only one genre of music for a year, which would it be?",
        "If you could write a letter to your future self, what’s one piece of advice you’d give?",
        "What's the most spontaneous thing you’ve ever done?",
        "What’s a memory you’ve held onto that most people wouldn’t think twice about?",
        "What is a compliment that has stuck with you?",
        "What is an insult that has stuck with you?",
        "What’s something you once believed as a kid that makes you laugh now?",
        "What’s a simple skill you think everyone should have, but few actually do?",
        "If you could pick one season to live in forever, which one would it be, and why?",
        "If you could make everyone follow one new law, what would it be?",
        "If you could bring back one fashion trend that’s gone out of style, what would it be?",
        "If you could see any part of the future for just five minutes, what would you look at?",
        "If you could pick one thing to be famous for (without effort), what would it be?",
        "If you could teach a class on one random topic, what would it be?",
        "If you could debunk one commonly accepted myth, which would it be?",
        "If you had to describe yourself in three words, what would they be?",
        "If you could live out one cliché from a movie, what would it be?",
        "What’s something unusual that always cheers you up?",
        "What’s a trend you missed out on but secretly wish you could have tried?"
    ]
}
